using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace NextAdmin.Infrastructure.CodeGeneration
{
    /// <summary>
    /// Partial 仓储代码生成器
    /// 根据仓储接口自动生成基础实现代码
    /// </summary>
    public class PartialRepositoryGenerator
    {
        private readonly string _outputDirectory;
        private readonly Assembly[] _assemblies;

        public PartialRepositoryGenerator(string outputDirectory, params Assembly[] assemblies)
        {
            _outputDirectory = outputDirectory ?? throw new ArgumentNullException(nameof(outputDirectory));
            _assemblies = assemblies ?? Array.Empty<Assembly>();
        }

        /// <summary>
        /// 生成所有仓储的 partial 实现
        /// </summary>
        public async Task GenerateAllRepositoriesAsync()
        {
            Console.WriteLine("=== Partial 仓储代码生成器 ===");
            Console.WriteLine($"输出目录: {_outputDirectory}");
            Console.WriteLine();

            if (!Directory.Exists(_outputDirectory))
            {
                Directory.CreateDirectory(_outputDirectory);
                Console.WriteLine($"✅ 已创建输出目录");
            }

            // 查找所有仓储接口
            var repositoryInterfaces = FindRepositoryInterfaces();
            Console.WriteLine($"📋 发现 {repositoryInterfaces.Count} 个仓储接口");
            Console.WriteLine();

            foreach (var interfaceType in repositoryInterfaces)
            {
                await GeneratePartialRepositoryAsync(interfaceType);
            }

            Console.WriteLine();
            Console.WriteLine("🎉 所有仓储代码生成完成！");
        }

        /// <summary>
        /// 生成单个仓储的 partial 实现
        /// </summary>
        public async Task GeneratePartialRepositoryAsync(Type interfaceType)
        {
            if (interfaceType == null || !interfaceType.IsInterface)
            {
                throw new ArgumentException("必须是接口类型", nameof(interfaceType));
            }

            var entityName = GetEntityNameFromInterface(interfaceType);
            var fileName = $"{entityName}Repository.Generated.cs";
            var filePath = Path.Combine(_outputDirectory, fileName);

            Console.WriteLine($"🔧 生成: {fileName}");

            var code = GenerateRepositoryCode(interfaceType, entityName);

            await File.WriteAllTextAsync(filePath, code, Encoding.UTF8);

            Console.WriteLine($"   ✅ 已生成: {filePath}");
        }

        /// <summary>
        /// 查找所有仓储接口
        /// </summary>
        private List<Type> FindRepositoryInterfaces()
        {
            var interfaces = new List<Type>();

            foreach (var assembly in _assemblies)
            {
                try
                {
                    var types = assembly.GetTypes()
                        .Where(t => t.IsInterface &&
                                    t.Name.StartsWith("I") &&
                                    t.Name.EndsWith("Repository") &&
                                    t.Name != "IBaseRepository")
                        .ToList();

                    interfaces.AddRange(types);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"⚠️  警告: 无法加载程序集 {assembly.FullName}: {ex.Message}");
                }
            }

            return interfaces;
        }

        /// <summary>
        /// 从接口名称提取实体名称
        /// </summary>
        private string GetEntityNameFromInterface(Type interfaceType)
        {
            var name = interfaceType.Name;
            if (name.StartsWith("I") && name.EndsWith("Repository"))
            {
                return name.Substring(1, name.Length - 11); // 移除 "I" 和 "Repository"
            }
            return name;
        }

        /// <summary>
        /// 生成仓储代码
        /// </summary>
        private string GenerateRepositoryCode(Type interfaceType, string entityName)
        {
            var sb = new StringBuilder();

            // 文件头注释
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 此文件由 PartialRepositoryGenerator 自动生成");
            sb.AppendLine($"// 生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// 警告: 请勿手动修改此文件，您的更改将在下次生成时丢失");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Using 声明
            var usings = GetRequiredUsings(interfaceType);
            foreach (var usingNamespace in usings.OrderBy(u => u))
            {
                sb.AppendLine($"using {usingNamespace};");
            }
            sb.AppendLine();

            // 命名空间
            sb.AppendLine($"namespace {interfaceType.Namespace?.Replace(".Interfaces.Repositories", ".Repositories") ?? "NextAdmin.Infrastructure.Repositories"}");
            sb.AppendLine("{");

            // 类声明
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entityName} 仓储自动生成的实现");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public partial class {entityName}Repository");
            sb.AppendLine("    {");

            // 生成方法实现
            var methods = GetCustomMethods(interfaceType);
            var isFirst = true;

            foreach (var method in methods)
            {
                if (!isFirst)
                {
                    sb.AppendLine();
                }
                isFirst = false;

                GenerateMethodImplementation(sb, method, entityName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 获取所需的 using 声明
        /// </summary>
        private HashSet<string> GetRequiredUsings(Type interfaceType)
        {
            var usings = new HashSet<string>
            {
                "System",
                "System.Collections.Generic",
                "System.Linq",
                "System.Threading.Tasks",
                "MongoDB.Driver",
                "MongoDB.Bson"
            };

            // 添加接口所在命名空间
            if (!string.IsNullOrEmpty(interfaceType.Namespace))
            {
                usings.Add(interfaceType.Namespace);
            }

            // 分析方法参数和返回值类型
            var methods = interfaceType.GetMethods();
            foreach (var method in methods)
            {
                // 返回类型
                if (!string.IsNullOrEmpty(method.ReturnType.Namespace))
                {
                    usings.Add(method.ReturnType.Namespace);
                }

                // 参数类型
                foreach (var parameter in method.GetParameters())
                {
                    if (!string.IsNullOrEmpty(parameter.ParameterType.Namespace))
                    {
                        usings.Add(parameter.ParameterType.Namespace);
                    }
                }
            }

            return usings;
        }

        /// <summary>
        /// 获取接口中的自定义方法（排除 IBaseRepository 的方法）
        /// </summary>
        private List<MethodInfo> GetCustomMethods(Type interfaceType)
        {
            var allMethods = interfaceType.GetMethods();
            
            // 排除 IBaseRepository<T> 的标准方法
            var standardMethodNames = new HashSet<string>
            {
                "GetByIdAsync", "GetAllAsync", "AddAsync", "UpdateAsync", 
                "DeleteAsync", "ExistsAsync", "CountAsync", "GetPagedAsync",
                "BulkAddAsync", "BulkUpdateAsync", "BulkDeleteAsync"
            };

            return allMethods
                .Where(m => !standardMethodNames.Contains(m.Name))
                .ToList();
        }

        /// <summary>
        /// 生成方法实现
        /// </summary>
        private void GenerateMethodImplementation(StringBuilder sb, MethodInfo method, string entityName)
        {
            // XML 注释
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// {method.Name} 的自动生成实现");
            sb.AppendLine("        /// </summary>");

            // 方法签名
            var parameters = method.GetParameters();
            var paramList = string.Join(", ", parameters.Select(p => $"{GetFriendlyTypeName(p.ParameterType)} {p.Name}"));
            var returnType = GetFriendlyTypeName(method.ReturnType);

            sb.AppendLine($"        public {returnType} {method.Name}({paramList})");
            sb.AppendLine("        {");

            // 生成方法体
            GenerateMethodBody(sb, method, entityName);

            sb.AppendLine("        }");
        }

        /// <summary>
        /// 生成方法体
        /// </summary>
        private void GenerateMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            var returnType = method.ReturnType;
            var isAsync = returnType.Name.Contains("Task");

            // 根据方法名推断实现逻辑
            var methodName = method.Name;

            if (methodName.StartsWith("GetBy") && methodName.EndsWith("Async"))
            {
                GenerateGetByMethodBody(sb, method, entityName);
            }
            else if (methodName.StartsWith("Search") && methodName.EndsWith("Async"))
            {
                GenerateSearchMethodBody(sb, method, entityName);
            }
            else if (methodName.StartsWith("Exists") && methodName.EndsWith("Async"))
            {
                GenerateExistsMethodBody(sb, method, entityName);
            }
            else if (methodName.StartsWith("GetCount") || methodName.Contains("Count"))
            {
                GenerateCountMethodBody(sb, method, entityName);
            }
            else if (methodName.StartsWith("BulkInsert") || methodName.StartsWith("Bulk"))
            {
                GenerateBulkMethodBody(sb, method, entityName);
            }
            else
            {
                // 默认实现：抛出未实现异常
                sb.AppendLine($"            throw new NotImplementedException(\"方法 {method.Name} 需要在 {entityName}Repository 的另一个 partial 部分中实现。\");");
            }
        }

        /// <summary>
        /// 生成 GetBy 方法体
        /// </summary>
        private void GenerateGetByMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            var parameters = method.GetParameters();
            var returnType = method.ReturnType;
            var isList = returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(Task<>)
                && returnType.GetGenericArguments()[0].IsGenericType
                && returnType.GetGenericArguments()[0].GetGenericTypeDefinition() == typeof(List<>);

            sb.AppendLine("            var filterBuilder = Builders<" + entityName + ">.Filter;");
            sb.AppendLine("            var filters = new List<FilterDefinition<" + entityName + ">>");
            sb.AppendLine("            {");
            sb.AppendLine("                filterBuilder.Eq(x => x.IsDeleted, false)");
            sb.AppendLine("            };");
            sb.AppendLine();

            // 为每个参数添加过滤条件
            foreach (var param in parameters)
            {
                var paramName = param.Name;
                var propertyName = char.ToUpper(paramName![0]) + paramName.Substring(1);

                if (param.ParameterType.Name.Contains("Nullable") || param.ParameterType.IsClass)
                {
                    sb.AppendLine($"            if ({paramName} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                filters.Add(filterBuilder.Eq(x => x.{propertyName}, {paramName}));");
                    sb.AppendLine("            }");
                }
                else
                {
                    sb.AppendLine($"            filters.Add(filterBuilder.Eq(x => x.{propertyName}, {paramName}));");
                }
            }

            sb.AppendLine();
            sb.AppendLine("            var filter = filterBuilder.And(filters);");
            sb.AppendLine();

            if (isList)
            {
                sb.AppendLine("            return await Collection.Find(filter)");
                sb.AppendLine("                .SortBy(x => x.CreateTime)");
                sb.AppendLine("                .ToListAsync();");
            }
            else
            {
                sb.AppendLine("            return await Collection.Find(filter).FirstOrDefaultAsync();");
            }
        }

        /// <summary>
        /// 生成 Search 方法体
        /// </summary>
        private void GenerateSearchMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            sb.AppendLine("            // TODO: 实现搜索逻辑");
            sb.AppendLine("            var filter = Builders<" + entityName + ">.Filter.Eq(x => x.IsDeleted, false);");
            sb.AppendLine("            return await Collection.Find(filter).ToListAsync();");
        }

        /// <summary>
        /// 生成 Exists 方法体
        /// </summary>
        private void GenerateExistsMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            sb.AppendLine("            var filter = Builders<" + entityName + ">.Filter.Eq(x => x.IsDeleted, false);");
            sb.AppendLine("            var count = await Collection.CountDocumentsAsync(filter);");
            sb.AppendLine("            return count > 0;");
        }

        /// <summary>
        /// 生成 Count 方法体
        /// </summary>
        private void GenerateCountMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            sb.AppendLine("            var filter = Builders<" + entityName + ">.Filter.Eq(x => x.IsDeleted, false);");
            sb.AppendLine("            return await Collection.CountDocumentsAsync(filter);");
        }

        /// <summary>
        /// 生成 Bulk 方法体
        /// </summary>
        private void GenerateBulkMethodBody(StringBuilder sb, MethodInfo method, string entityName)
        {
            sb.AppendLine("            // TODO: 实现批量操作逻辑");
            sb.AppendLine($"            throw new NotImplementedException(\"方法 {method.Name} 需要在 {entityName}Repository 的另一个 partial 部分中实现。\");");
        }

        /// <summary>
        /// 获取友好的类型名称
        /// </summary>
        private string GetFriendlyTypeName(Type type)
        {
            if (!type.IsGenericType)
            {
                return type.Name switch
                {
                    "Void" => "void",
                    "String" => "string",
                    "Int32" => "int",
                    "Int64" => "long",
                    "Boolean" => "bool",
                    "Double" => "double",
                    "Decimal" => "decimal",
                    _ => type.Name
                };
            }

            var genericTypeName = type.Name.Split('`')[0];
            var genericArgs = string.Join(", ", type.GetGenericArguments().Select(GetFriendlyTypeName));

            return $"{genericTypeName}<{genericArgs}>";
        }
    }
}
